// Code generated by protoc-gen-go.
// source: build.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	build.proto
	job.proto
	project.proto

It has these top-level messages:
	Build
	BuildStatus
	Job
	Project
	Repo
	Kubernetes
	Github
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Build struct {
	// ID is the unique ID for a webhook event.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// ProjectID is the computed name of the project (brigade-aeff2343a3234ff)
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	// Type is the event type (push, pull_request, tag, etc.)
	Type string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	// Provider is the name of the service that caused the event (github, vsts, cron, ...)
	Provider string `protobuf:"bytes,4,opt,name=provider" json:"provider,omitempty"`
	// Commit is the ID of the VCS version, such as the Git commit SHA.
	Commit string `protobuf:"bytes,5,opt,name=commit" json:"commit,omitempty"`
	// Payload is the raw data as received by the webhook.
	Payload []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	// Script is the brigadeJS to be executed.
	Script []byte `protobuf:"bytes,7,opt,name=script,proto3" json:"script,omitempty"`
}

func (m *Build) Reset()                    { *m = Build{} }
func (m *Build) String() string            { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()               {}
func (*Build) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BuildStatus struct {
	BuildId string `protobuf:"bytes,1,opt,name=build_id,json=buildId" json:"build_id,omitempty"`
	// CreationTime is a timestamp representing the server time when this object was
	// created. It is not guaranteed to be set in happens-before order across separate operations.
	CreationTime *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=creation_time,json=creationTime" json:"creation_time,omitempty"`
	// StartTime is the time the job started.
	StartTime *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	// EndTime is the time the job completed. This may not be present
	// if the job has not completed.
	EndTime *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	// ExitCode is the exit code of the job. This may not be present
	// if the job has not completed.
	ExitCode int32 `protobuf:"varint,7,opt,name=exit_code,json=exitCode" json:"exit_code,omitempty"`
	// Status is a textual representation of the job's running status
	Status JobStatus `protobuf:"varint,8,opt,name=status,enum=pb.JobStatus" json:"status,omitempty"`
}

func (m *BuildStatus) Reset()                    { *m = BuildStatus{} }
func (m *BuildStatus) String() string            { return proto.CompactTextString(m) }
func (*BuildStatus) ProtoMessage()               {}
func (*BuildStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BuildStatus) GetCreationTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreationTime
	}
	return nil
}

func (m *BuildStatus) GetStartTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *BuildStatus) GetEndTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func init() {
	proto.RegisterType((*Build)(nil), "pb.Build")
	proto.RegisterType((*BuildStatus)(nil), "pb.BuildStatus")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Brigade service

type BrigadeClient interface {
	CreateBuild(ctx context.Context, in *Build, opts ...grpc.CallOption) (Brigade_CreateBuildClient, error)
}

type brigadeClient struct {
	cc *grpc.ClientConn
}

func NewBrigadeClient(cc *grpc.ClientConn) BrigadeClient {
	return &brigadeClient{cc}
}

func (c *brigadeClient) CreateBuild(ctx context.Context, in *Build, opts ...grpc.CallOption) (Brigade_CreateBuildClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Brigade_serviceDesc.Streams[0], c.cc, "/pb.Brigade/CreateBuild", opts...)
	if err != nil {
		return nil, err
	}
	x := &brigadeCreateBuildClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Brigade_CreateBuildClient interface {
	Recv() (*BuildStatus, error)
	grpc.ClientStream
}

type brigadeCreateBuildClient struct {
	grpc.ClientStream
}

func (x *brigadeCreateBuildClient) Recv() (*BuildStatus, error) {
	m := new(BuildStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Brigade service

type BrigadeServer interface {
	CreateBuild(*Build, Brigade_CreateBuildServer) error
}

func RegisterBrigadeServer(s *grpc.Server, srv BrigadeServer) {
	s.RegisterService(&_Brigade_serviceDesc, srv)
}

func _Brigade_CreateBuild_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Build)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BrigadeServer).CreateBuild(m, &brigadeCreateBuildServer{stream})
}

type Brigade_CreateBuildServer interface {
	Send(*BuildStatus) error
	grpc.ServerStream
}

type brigadeCreateBuildServer struct {
	grpc.ServerStream
}

func (x *brigadeCreateBuildServer) Send(m *BuildStatus) error {
	return x.ServerStream.SendMsg(m)
}

var _Brigade_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Brigade",
	HandlerType: (*BrigadeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateBuild",
			Handler:       _Brigade_CreateBuild_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "build.proto",
}

func init() { proto.RegisterFile("build.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x5f, 0x8b, 0xd4, 0x30,
	0x14, 0xc5, 0x6d, 0xdd, 0xfe, 0xbb, 0xdd, 0x5d, 0x21, 0x0f, 0x12, 0x2b, 0xc2, 0x30, 0x20, 0xcc,
	0x8b, 0xad, 0x8c, 0x08, 0x8a, 0x0f, 0xc2, 0xee, 0xd3, 0xfa, 0x58, 0x7d, 0x2f, 0x49, 0x13, 0x6b,
	0x96, 0xb6, 0x09, 0x69, 0x2a, 0xce, 0xa7, 0xf1, 0x2b, 0xf8, 0x11, 0x25, 0xb7, 0xed, 0xec, 0xe3,
	0xbc, 0xdd, 0x73, 0xce, 0xfc, 0x32, 0xf7, 0x9e, 0x42, 0xce, 0x67, 0xd5, 0x8b, 0xd2, 0x58, 0xed,
	0x34, 0x09, 0x0d, 0x2f, 0xbe, 0x74, 0xca, 0xfd, 0x9a, 0x79, 0xd9, 0xea, 0xa1, 0xea, 0x74, 0xcf,
	0xc6, 0xae, 0xc2, 0x90, 0xcf, 0x3f, 0x2b, 0xe3, 0x4e, 0x46, 0x4e, 0x95, 0x53, 0x83, 0x9c, 0x1c,
	0x1b, 0xcc, 0xd3, 0xb4, 0x3c, 0x50, 0x64, 0x8f, 0x9a, 0x2f, 0xe3, 0xfe, 0x5f, 0x00, 0xd1, 0x9d,
	0x7f, 0x9b, 0xdc, 0x42, 0xa8, 0x04, 0x0d, 0x76, 0xc1, 0x21, 0xab, 0x43, 0x25, 0xc8, 0x1b, 0x00,
	0x63, 0xf5, 0xa3, 0x6c, 0x5d, 0xa3, 0x04, 0x0d, 0xd1, 0xcf, 0x56, 0xe7, 0x41, 0x10, 0x02, 0x57,
	0xfe, 0x6f, 0xe8, 0x73, 0x0c, 0x70, 0x26, 0x05, 0xa4, 0xc6, 0xea, 0xdf, 0x4a, 0x48, 0x4b, 0xaf,
	0xd0, 0x3f, 0x6b, 0xf2, 0x12, 0xe2, 0x56, 0x0f, 0x83, 0x72, 0x34, 0xc2, 0x64, 0x55, 0x84, 0x42,
	0x62, 0xd8, 0xa9, 0xd7, 0x4c, 0xd0, 0x78, 0x17, 0x1c, 0xae, 0xeb, 0x4d, 0x7a, 0x62, 0x6a, 0xad,
	0x32, 0x8e, 0x26, 0x18, 0xac, 0x6a, 0xff, 0x37, 0x84, 0x1c, 0x57, 0xfe, 0xee, 0x98, 0x9b, 0x27,
	0xf2, 0x0a, 0x52, 0x6c, 0xa7, 0x39, 0xaf, 0x9f, 0xa0, 0x7e, 0x10, 0xe4, 0x2b, 0xdc, 0xb4, 0x56,
	0x32, 0xa7, 0xf4, 0xd8, 0xf8, 0x12, 0x70, 0xab, 0xfc, 0x58, 0x94, 0x9d, 0xd6, 0x5d, 0x2f, 0xcb,
	0xad, 0xb2, 0xf2, 0xc7, 0xd6, 0x50, 0x7d, 0xbd, 0x01, 0xde, 0x22, 0x9f, 0x01, 0x26, 0xc7, 0xac,
	0x5b, 0xe8, 0xe8, 0x22, 0x9d, 0xe1, 0xaf, 0x11, 0xfd, 0x08, 0xa9, 0x1c, 0xc5, 0x02, 0xc6, 0x17,
	0xc1, 0x44, 0x8e, 0x02, 0xb1, 0xd7, 0x90, 0xc9, 0x3f, 0xca, 0x35, 0xad, 0x16, 0x12, 0x0f, 0x8f,
	0xea, 0xd4, 0x1b, 0xf7, 0x5a, 0x48, 0xf2, 0x16, 0xe2, 0x09, 0x8f, 0xa6, 0xe9, 0x2e, 0x38, 0xdc,
	0x1e, 0x6f, 0x4a, 0xc3, 0xcb, 0x6f, 0x9a, 0x2f, 0x4d, 0xd4, 0x6b, 0x78, 0xfc, 0x04, 0xc9, 0x9d,
	0x55, 0x1d, 0x13, 0x92, 0xbc, 0x83, 0xfc, 0xde, 0x1f, 0x24, 0x97, 0x8f, 0x9c, 0x79, 0x00, 0xc7,
	0xe2, 0xc5, 0x79, 0x5c, 0xe8, 0xfd, 0xb3, 0xf7, 0x01, 0x8f, 0x71, 0xb5, 0x0f, 0xff, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x57, 0x69, 0xd0, 0x47, 0x70, 0x02, 0x00, 0x00,
}
